name: automate deploy luma

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build app.yaml
        run: |- 
              echo "${{ secrets.APP_YAML }}"  > app.yaml

      - name: Install dependencies
        run: npm i

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Google App Engine
        run: gcloud app deploy app.yaml --quiet

      - name: Get App URL
        id: get-url
        run: echo "URL=https://${{ secrets.GCP_PROJECT_ID }}.appspot.com" >> $GITHUB_ENV

  messageSlack:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Notification Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: deploys-logs
          SLACK_TITLE: "Deployment Notification"
          SLACK_USERNAME: "GitHub Actions Bot"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            *Deployment Status*
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref }}
            *Commit:* ${{ github.sha }}
            *Author:* ${{ github.actor }}
            *Message:* ${{ github.event.head_commit.message }}
            *Status:* ${{ job.status }}
            *Job URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            *App Engine URL:* ${{ env.URL }}
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || job.status == 'failure' && 'danger' || 'warning' }}
      - name: Failure Notification Slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: deploys
          SLACK_TITLE: "Deployment Failure Notification"
          SLACK_USERNAME: "GitHub Actions Bot"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            *Deployment Status*
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref }}
            *Commit:* ${{ github.sha }}
            *Author:* ${{ github.actor }}
            *Message:* ${{ github.event.head_commit.message }}
            *Status:* Deploy failed
            *Job URL:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            *App Engine URL:* ${{ env.URL }}
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_COLOR: danger

      





